### ISSUE TITLE
Fix position when screen is resized

### ISSUE THREAD

**Issue by zenorocha** [metal/metal-autocomplete#1]
![screen shot 2016-02-03 at 2 00 47 pm](https://cloud.githubusercontent.com/assets/398893/12790043/4eb86ee2-ca55-11e5-962d-26284b62964d.png)

**Comment by eduardolundgren** [comment]
This can be fixed by listening window resize and invoking the align method.
/cc @mairatma Could you look at this when you have a chance?

**Comment by mairatma** [comment]
Sure, it's similar to what we already have for metal-dropdown and metal-tooltip. Maybe we could even just use metal-dropdown for this, would that be ok? Otherwise I'll just use Align directly like you said.

**Comment by zenorocha** [comment]
:tada:
