### ISSUE TITLE
Provide a css class when component does not fit the screen

### ISSUE THREAD

**Issue by zenorocha** [metal/metal-autocomplete#2]
Basically, what I need is a css class to style the list in a certain way when the component is on bottom and another css class when the component is on the top.

![screen shot 2016-02-03 at 2 01 51 pm](https://cloud.githubusercontent.com/assets/398893/12790033/422d7b22-ca55-11e5-8594-fbe4d17c01cf.png)

**Comment by zenorocha** [comment]
@eduardolundgren is there a way to look the auto positioning feature?

**Comment by mairatma** [comment]
We do something similar to do this for metal-tooltip already, so this should be simple to do once we have https://github.com/metal/metal-autocomplete/issues/1 working too :)

**Comment by zenorocha** [comment]
:tada:
